nombre = "Francisco"
print(nombre.upper())
print(nombre.capitalize())
print(nombre.strip())
print(nombre.lower())
print(nombre.replace('o', 'a'))
print(nombre[0])
print(len(nombre))

print(nombre[0:3])
print(nombre[:3])
print(nombre[3:])
print(nombre[1:7])
print(nombre[1:7:2])
print(nombre[::])
print(nombre[::-1])